### ISSUE TITLE
Add Description

### ISSUE THREAD

**Issue by AmitManna99** [AmitManna99/the-git-jam-demo#1]
### Add Event Details

_Add this Details in the left side of **Register Here** Button_

**Event Details**
Hacktoberfest® is open to everyone in our global community. Pull requests can be made in any GitHub-hosted repositories/projects. You can sign up anytime between October 1 and October 31.
To earn your Hacktoberfest tee or tree reward, you must register and make four valid pull requests (PRs) between October 1-31 (in any time zone). This year, the first 70,000 participants who successfully complete the challenge will be eligible to receive a prize.

**Comment by SalmonKing72** [comment]
I'd like to contribute. Hoping to be able to pick this one up.

**Comment by SalmonKing72** [comment]
@AmitManna99 what was I missing regarding acceptance?
